- name: Ping Servers
  hosts: all
  become: yes
 
  tasks:
  - name: Task ping
    ping:
 
  - name: Task yum update
    yum:
      update_cache: yes
 
  - name: Install MC
    yum:
      name: mc
      state: latest
  - name: Copy File
    copy:
      src: test.txt
      dest: /home/ansible/files
      mode: 0777
  - name: MC
    yum:
      name: mc
      state: absent
  - name: Installing package
    yum:
      name:
        - net-tools
        - tree
        - htop
        - mc
      state: latest

