- name: Servers
  hosts: all
  become: yes
 
  vars:
    packages:
      - net-tools
      - tree
      - htop
  tasks:
  - name: Installing package
    yum:
      name: "{{packages}}"
      state: latest

  - name: Copy File
    copy:
      src: test.txt
      dest: /home/ansible/files
      mode: 0777
